enum AppLanguage { ru, tj, en }

abstract final class AppStrings {
  static const Map<String, Map<String, String>> all = {
    'ru': {
      'appName': 'ДДМИТ',
      'productName': 'UniBook',
      'splashSubtitle': 'UniBook',
      'welcome': 'Добро пожаловать',
      'guest': 'Гость',
      'home': 'Главная',
      'catalog': 'Каталог',
      'books': 'Книги',
      'departments': 'Кафедры',
      'favorites': 'Избранное',
      'profile': 'Профиль',
      'users': 'Пользователи',
      'search': 'Поиск',
      'searchHint': 'Поиск книг, авторов, кафедр',
      'newArrivals': 'Новые поступления',
      'quickAccess': 'Быстрый доступ',
      'openLibrary': 'Открыть библиотеку',
      'theme': 'Тема',
      'darkTheme': 'Тёмная',
      'lightTheme': 'Светлая',
      'language': 'Язык',
      'settings': 'Настройки',
      'loading': 'Загрузка...',
      'emptyBooks': 'Книги пока не добавлены',
      'emptyDepartments': 'Кафедры не найдены',
      'errorGeneric': 'Произошла ошибка',
      'tryAgain': 'Повторить',
      'adminPanel': 'Панель администратора',
      'adminLogin': 'Вход администратора',
      'adminOnlyLoginHint': 'Только для преподавателя/администратора',
      'login': 'Войти',
      'logout': 'Выйти',
      'email': 'Email',
      'password': 'Пароль',
      'forgotPassword': 'Забыли пароль?',
      'resetPasswordSent': 'Проверьте почту для сброса пароля',
      'invalidCredentials': 'Неверный email или пароль',
      'adminAccessDenied': 'Доступ только для администратора/преподавателя',
      'department': 'Кафедра',
      'chooseDepartment': 'Выберите кафедру',
      'author': 'Автор',
      'year': 'Год',
      'subject': 'Предмет',
      'bookCount': 'книг',
      'teacher': 'Преподаватель',
      'administrator': 'Администратор',
      'student': 'Студент',
      'notAuthorized': 'Не авторизован',
      'signInToAdmin': 'Войти в админ-зону',
      'changeTheme': 'Сменить тему',
      'changeLanguage': 'Сменить язык',
      'openAdminPanel': 'Открыть админ-панель',
      'logoutConfirm': 'Выйти из аккаунта?',
      'cancel': 'Отмена',
      'uploadBook': 'Добавить книгу',
      'saveBook': 'Сохранить книгу',
      'bookInfo': 'Информация о книге',
      'files': 'Файлы',
      'pickPdf': 'Выбрать PDF файл',
      'maxFileSize': 'Максимум 50 МБ',
      'coverOptional': 'Добавить обложку (необязательно)',
      'coverSelected': 'Обложка выбрана',
      'bookUploaded': 'Книга успешно загружена',
      'createAccount': 'Создать аккаунт',
      'name': 'Имя',
      'fullName': 'Имя и фамилия',
      'role': 'Роль',
      'confirmPassword': 'Подтвердите пароль',
      'teacherCode': 'Код учителя',
      'register': 'Зарегистрироваться',
      'success': 'Успешно',
      'save': 'Сохранить',
      'edit': 'Изменить',
      'delete': 'Удалить',
      'loadingStats': 'Загрузка статистики...',
      'noResults': 'Ничего не найдено',
      'booksUploaded': 'Книг загружено',
      'usersCount': 'Пользователей',
      'departmentsCount': 'Кафедр',
      'bookmarksAndNotes': 'Закладки и заметки',
      'bookmarks': 'Закладки',
      'notes': 'Заметки',
      'addBookmark': 'Добавить закладку',
      'removeBookmark': 'Убрать закладку',
      'addNote': 'Добавить заметку',
      'bookmarkAdded': 'Закладка добавлена',
      'bookmarkRemoved': 'Закладка удалена',
      'noteAdded': 'Заметка добавлена',
      'noteSaved': 'Заметка сохранена',
      'editNote': 'Редактировать заметку',
      'noteTextHint': 'Текст заметки...',
      'addNoteForPage': 'Заметка',
      'addNoteHint': 'Введите заметку...',
      'noBookmarks': 'Нет закладок',
      'noBookmarksHint': 'Добавляйте закладки во время чтения',
      'noNotes': 'Нет заметок',
      'noNotesHint': 'Добавляйте заметки во время чтения',
      'unknownBook': 'Книга',
      'page': 'Страница',
      'pageCut': 'Стр.',
    },
    'tj': {
      'appName': 'ДДМИТ',
      'productName': 'UniBook',
      'splashSubtitle': 'UniBook',
      'welcome': 'Хуш омадед',
      'guest': 'Меҳмон',
      'home': 'Асосӣ',
      'catalog': 'Каталог',
      'books': 'Китобҳо',
      'departments': 'Кафедраҳо',
      'favorites': 'Дӯстдоштаҳо',
      'profile': 'Профил',
      'users': 'Корбарон',
      'search': 'Ҷустуҷӯ',
      'searchHint': 'Ҷустуҷӯи китоб, муаллиф, кафедра',
      'newArrivals': 'Китобҳои нав',
      'quickAccess': 'Дастрасии зуд',
      'openLibrary': 'Кушодани китобхона',
      'theme': 'Мавзӯъ',
      'darkTheme': 'Торик',
      'lightTheme': 'Равшан',
      'language': 'Забон',
      'settings': 'Танзимот',
      'loading': 'Боркунӣ...',
      'emptyBooks': 'Ҳоло китоб нест',
      'emptyDepartments': 'Кафедра ёфт нашуд',
      'errorGeneric': 'Хатогӣ рух дод',
      'tryAgain': 'Боз кӯшиш кунед',
      'adminPanel': 'Панели админ',
      'adminLogin': 'Вуруди админ',
      'adminOnlyLoginHint': 'Танҳо барои омӯзгор/админ',
      'login': 'Ворид шудан',
      'logout': 'Баромадан',
      'email': 'Email',
      'password': 'Рамз',
      'forgotPassword': 'Рамзро фаромӯш кардед?',
      'resetPasswordSent': 'Почтаро барои барқарорсозӣ санҷед',
      'invalidCredentials': 'Email ё рамз нодуруст аст',
      'adminAccessDenied': 'Дастрасӣ танҳо барои омӯзгор/админ',
      'department': 'Кафедра',
      'chooseDepartment': 'Кафедраро интихоб кунед',
      'author': 'Муаллиф',
      'year': 'Сол',
      'subject': 'Фан',
      'bookCount': 'китоб',
      'teacher': 'Омӯзгор',
      'administrator': 'Админ',
      'student': 'Донишҷӯ',
      'notAuthorized': 'Ворид нашудааст',
      'signInToAdmin': 'Ба админ-зона ворид шавед',
      'changeTheme': 'Иваз кардани мавзӯъ',
      'changeLanguage': 'Иваз кардани забон',
      'openAdminPanel': 'Кушодани панели админ',
      'logoutConfirm': 'Аз аккаунт бароед?',
      'cancel': 'Бекор кардан',
      'uploadBook': 'Иловаи китоб',
      'saveBook': 'Сабти китоб',
      'bookInfo': 'Маълумот дар бораи китоб',
      'files': 'Файлҳо',
      'pickPdf': 'Интихоби PDF',
      'maxFileSize': 'Ҳадди аксар 50 МБ',
      'coverOptional': 'Иловаи муқова (ихтиёрӣ)',
      'coverSelected': 'Муқова интихоб шуд',
      'bookUploaded': 'Китоб бомуваффақият бор шуд',
      'createAccount': 'Эҷоди ҳисоб',
      'name': 'Ном',
      'fullName': 'Ном ва насаб',
      'role': 'Нақш',
      'confirmPassword': 'Тасдиқи рамз',
      'teacherCode': 'Коди омӯзгор',
      'register': 'Бақайдгирӣ',
      'success': 'Муваффақ шуд',
      'save': 'Сабт кардан',
      'edit': 'Таҳрир',
      'delete': 'Нест кардан',
      'loadingStats': 'Боркунии омор...',
      'noResults': 'Ҳеҷ чиз ёфт нашуд',
      'booksUploaded': 'Китобҳои боршуда',
      'usersCount': 'Корбарон',
      'departmentsCount': 'Кафедраҳо',
      'bookmarksAndNotes': 'Нишонаҳо ва қайдҳо',
      'bookmarks': 'Нишонаҳо',
      'notes': 'Қайдҳо',
      'addBookmark': 'Иловаи нишона',
      'removeBookmark': 'Нест кардани нишона',
      'addNote': 'Иловаи қайд',
      'bookmarkAdded': 'Нишона илова шуд',
      'bookmarkRemoved': 'Нишона нест шуд',
      'noteAdded': 'Қайд илова шуд',
      'noteSaved': 'Қайд сабт шуд',
      'editNote': 'Таҳрири қайд',
      'noteTextHint': 'Матни қайд...',
      'addNoteForPage': 'Қайд',
      'addNoteHint': 'Қайд нависед...',
      'noBookmarks': 'Нишона нест',
      'noBookmarksHint': 'Ҳангоми хондан нишона илова кунед',
      'noNotes': 'Қайд нест',
      'noNotesHint': 'Ҳангоми хондан қайд илова кунед',
      'unknownBook': 'Китоб',
      'page': 'Саҳифа',
      'pageCut': 'Саҳ.',
    },
    'en': {
      'appName': 'DDMIT',
      'productName': 'UniBook',
      'splashSubtitle': 'UniBook',
      'welcome': 'Welcome',
      'guest': 'Guest',
      'home': 'Home',
      'catalog': 'Catalog',
      'books': 'Books',
      'departments': 'Departments',
      'favorites': 'Favorites',
      'profile': 'Profile',
      'users': 'Users',
      'search': 'Search',
      'searchHint': 'Search books, authors, departments',
      'newArrivals': 'New arrivals',
      'quickAccess': 'Quick access',
      'openLibrary': 'Open library',
      'theme': 'Theme',
      'darkTheme': 'Dark',
      'lightTheme': 'Light',
      'language': 'Language',
      'settings': 'Settings',
      'loading': 'Loading...',
      'emptyBooks': 'No books yet',
      'emptyDepartments': 'No departments found',
      'errorGeneric': 'Something went wrong',
      'tryAgain': 'Try again',
      'adminPanel': 'Admin panel',
      'adminLogin': 'Admin login',
      'adminOnlyLoginHint': 'Teacher/admin access only',
      'login': 'Log in',
      'logout': 'Log out',
      'email': 'Email',
      'password': 'Password',
      'forgotPassword': 'Forgot password?',
      'resetPasswordSent': 'Check your email to reset password',
      'invalidCredentials': 'Invalid email or password',
      'adminAccessDenied': 'Access is restricted to teacher/admin',
      'department': 'Department',
      'chooseDepartment': 'Choose department',
      'author': 'Author',
      'year': 'Year',
      'subject': 'Subject',
      'bookCount': 'books',
      'teacher': 'Teacher',
      'administrator': 'Administrator',
      'student': 'Student',
      'notAuthorized': 'Not signed in',
      'signInToAdmin': 'Sign in to admin area',
      'changeTheme': 'Change theme',
      'changeLanguage': 'Change language',
      'openAdminPanel': 'Open admin panel',
      'logoutConfirm': 'Log out from account?',
      'cancel': 'Cancel',
      'uploadBook': 'Add book',
      'saveBook': 'Save book',
      'bookInfo': 'Book information',
      'files': 'Files',
      'pickPdf': 'Pick PDF file',
      'maxFileSize': 'Max 50 MB',
      'coverOptional': 'Add cover (optional)',
      'coverSelected': 'Cover selected',
      'bookUploaded': 'Book uploaded successfully',
      'createAccount': 'Create account',
      'name': 'Name',
      'fullName': 'Full name',
      'role': 'Role',
      'confirmPassword': 'Confirm password',
      'teacherCode': 'Teacher code',
      'register': 'Register',
      'success': 'Success',
      'save': 'Save',
      'edit': 'Edit',
      'delete': 'Delete',
      'loadingStats': 'Loading stats...',
      'noResults': 'Nothing found',
      'booksUploaded': 'Books uploaded',
      'usersCount': 'Users',
      'departmentsCount': 'Departments',
      'bookmarksAndNotes': 'Bookmarks & Notes',
      'bookmarks': 'Bookmarks',
      'notes': 'Notes',
      'addBookmark': 'Add bookmark',
      'removeBookmark': 'Remove bookmark',
      'addNote': 'Add note',
      'bookmarkAdded': 'Bookmark added',
      'bookmarkRemoved': 'Bookmark removed',
      'noteAdded': 'Note added',
      'noteSaved': 'Note saved',
      'editNote': 'Edit note',
      'noteTextHint': 'Note text...',
      'addNoteForPage': 'Note',
      'addNoteHint': 'Enter a note...',
      'noBookmarks': 'No bookmarks',
      'noBookmarksHint': 'Add bookmarks while reading',
      'noNotes': 'No notes',
      'noNotesHint': 'Add notes while reading',
      'unknownBook': 'Book',
      'page': 'Page',
      'pageCut': 'P.',
    },
  };

  static String translate(String key, {String languageCode = 'ru'}) {
    return all[languageCode]?[key] ?? all['ru']?[key] ?? key;
  }
}