class FacultyInfo {
  const FacultyInfo({required this.id, required this.name, required this.shortName});

  final String id;
  final String name;
  final String shortName;
}

const tgfeuAddress = '734067, г. Душанбе, ул. Нахимова, 64/14';
const tgfeuPhone = '+992 37 231 0843';

const faculties = <FacultyInfo>[
  FacultyInfo(
    id: 'faculty_international',
    name: 'Факультет международных экономических отношений',
    shortName: 'МЭО',
  ),
  FacultyInfo(
    id: 'faculty_accounting',
    name: 'Факультет бухгалтерского учёта и статистики',
    shortName: 'БУС',
  ),
  FacultyInfo(
    id: 'faculty_economics',
    name: 'Факультет экономики и государственного управления',
    shortName: 'ЭГУ',
  ),
  FacultyInfo(
    id: 'faculty_management',
    name: 'Факультет менеджмента и экономического права',
    shortName: 'МЭП',
  ),
  FacultyInfo(
    id: 'faculty_digital',
    name: 'Факультет цифровой экономики и инновационных технологий',
    shortName: 'ЦЭИТ',
  ),
  FacultyInfo(
    id: 'faculty_finance',
    name: 'Факультет финансов и кредита',
    shortName: 'ФиК',
  ),
  FacultyInfo(
    id: 'faculty_customs',
    name: 'Факультет таможенной деятельности и экономической безопасности',
    shortName: 'ТДЭБ',
  ),
];

String facultyNameById(String id) {
  final matches = faculties.where((f) => f.id == id).toList();
  if (matches.isEmpty) return 'Факультет не указан';
  return matches.first.name;
}

const tgfeuDepartments = <Map<String, dynamic>>[
  {
    'id': 'dept_world_economy',
    'name': 'Кафедра мировой экономики',
    'code': 'ME',
    'facultyId': 'faculty_international',
    'building': 'Корпус 1',
    'room': '201',
    'icon': 'public',
    'color': '#1565C0',
  },
  {
    'id': 'dept_customs',
    'name': 'Кафедра таможенной деятельности',
    'code': 'TAM',
    'facultyId': 'faculty_customs',
    'building': 'Корпус 2',
    'room': '105',
    'icon': 'security',
    'color': '#4A148C',
  },
  {
    'id': 'dept_fin_economics',
    'name': 'Кафедра финансовой экономики',
    'code': 'FE',
    'facultyId': 'faculty_finance',
    'building': 'Корпус 1',
    'room': '310',
    'icon': 'trending_up',
    'color': '#00695C',
  },
  {
    'id': 'dept_banking',
    'name': 'Кафедра банковской деятельности',
    'code': 'BANK',
    'facultyId': 'faculty_finance',
    'building': 'Корпус 2',
    'room': '215',
    'icon': 'account_balance',
    'color': '#1B5E20',
  },
  {
    'id': 'dept_finance',
    'name': 'Кафедра финансов',
    'code': 'FIN',
    'facultyId': 'faculty_finance',
    'building': 'Корпус 1',
    'room': '205',
    'icon': 'payments',
    'color': '#0D47A1',
  },
  {
    'id': 'dept_econ_analysis',
    'name': 'Кафедра экономического анализа и статистики',
    'code': 'EAS',
    'facultyId': 'faculty_accounting',
    'building': 'Корпус 2',
    'room': '301',
    'icon': 'bar_chart',
    'color': '#E65100',
  },
  {
    'id': 'dept_audit',
    'name': 'Кафедра аудита и ревизии',
    'code': 'AUD',
    'facultyId': 'faculty_accounting',
    'building': 'Корпус 2',
    'room': '302',
    'icon': 'fact_check',
    'color': '#880E4F',
  },
  {
    'id': 'dept_accounting',
    'name': 'Кафедра бухгалтерского учёта',
    'code': 'ACC',
    'facultyId': 'faculty_accounting',
    'building': 'Корпус 2',
    'room': '210',
    'icon': 'calculate',
    'color': '#2E7D32',
  },
  {
    'id': 'dept_fin_management',
    'name': 'Кафедра финансового менеджмента',
    'code': 'FM',
    'facultyId': 'faculty_management',
    'building': 'Корпус 1',
    'room': '401',
    'icon': 'manage_accounts',
    'color': '#6A1B9A',
  },
  {
    'id': 'dept_tax',
    'name': 'Кафедра налогообложения и страхования',
    'code': 'TAX',
    'facultyId': 'faculty_customs',
    'building': 'Корпус 2',
    'room': '110',
    'icon': 'receipt_long',
    'color': '#BF360C',
  },
  {
    'id': 'dept_applied_info',
    'name': 'Кафедра прикладной информатики в экономике',
    'code': 'AIE',
    'facultyId': 'faculty_digital',
    'building': 'Корпус 3',
    'room': '101',
    'icon': 'computer',
    'color': '#0277BD',
  },
  {
    'id': 'dept_digital',
    'name': 'Кафедра цифровой экономики и логистики',
    'code': 'DEL',
    'facultyId': 'faculty_digital',
    'building': 'Корпус 3',
    'room': '205',
    'icon': 'devices',
    'color': '#006064',
  },
  {
    'id': 'dept_info_systems',
    'name': 'Кафедра информационно-инновационных систем в экономике',
    'code': 'IIS',
    'facultyId': 'faculty_digital',
    'building': 'Корпус 3',
    'room': '210',
    'icon': 'hub',
    'color': '#1A237E',
  },
  {
    'id': 'dept_intl_finance',
    'name': 'Кафедра международных финансово-кредитных отношений',
    'code': 'IFC',
    'facultyId': 'faculty_international',
    'building': 'Корпус 1',
    'room': '315',
    'icon': 'currency_exchange',
    'color': '#004D40',
  },
  {
    'id': 'dept_management',
    'name': 'Кафедра менеджмента',
    'code': 'MAN',
    'facultyId': 'faculty_management',
    'building': 'Корпус 1',
    'room': '405',
    'icon': 'business_center',
    'color': '#37474F',
  },
  {
    'id': 'dept_econ_law',
    'name': 'Кафедра экономического права',
    'code': 'LAW',
    'facultyId': 'faculty_management',
    'building': 'Корпус 1',
    'room': '410',
    'icon': 'gavel',
    'color': '#3E2723',
  },
  {
    'id': 'dept_enterprise',
    'name': 'Кафедра экономики предприятий и предпринимательства',
    'code': 'EEE',
    'facultyId': 'faculty_economics',
    'building': 'Корпус 2',
    'room': '401',
    'icon': 'store',
    'color': '#827717',
  },
  {
    'id': 'dept_econ_theory',
    'name': 'Кафедра экономической теории',
    'code': 'ET',
    'facultyId': 'faculty_economics',
    'building': 'Корпус 2',
    'room': '405',
    'icon': 'school',
    'color': '#558B2F',
  },
  {
    'id': 'dept_foreign_lang',
    'name': 'Кафедра иностранных языков',
    'code': 'FL',
    'facultyId': 'faculty_economics',
    'building': 'Корпус 1',
    'room': '115',
    'icon': 'language',
    'color': '#AD1457',
  },
  {
    'id': 'dept_tj_ru_lang',
    'name': 'Кафедра таджикского и русского языков',
    'code': 'TRL',
    'facultyId': 'faculty_economics',
    'building': 'Корпус 1',
    'room': '120',
    'icon': 'translate',
    'color': '#283593',
  },
  {
    'id': 'dept_math_it',
    'name': 'Кафедра математики и информационных технологий',
    'code': 'MIT',
    'facultyId': 'faculty_digital',
    'building': 'Корпус 3',
    'room': '301',
    'icon': 'functions',
    'color': '#0288D1',
  },
  {
    'id': 'dept_sport',
    'name': 'Кафедра физического воспитания',
    'code': 'SPORT',
    'facultyId': 'faculty_economics',
    'building': 'Корпус 4',
    'room': 'Спортзал',
    'icon': 'sports',
    'color': '#2E7D32',
  },
  {
    'id': 'dept_history',
    'name': 'Кафедра истории и философии',
    'code': 'HIST',
    'facultyId': 'faculty_economics',
    'building': 'Корпус 1',
    'room': '225',
    'icon': 'history_edu',
    'color': '#4E342E',
  },
  {
    'id': 'dept_statistics',
    'name': 'Кафедра статистики',
    'code': 'STAT',
    'facultyId': 'faculty_accounting',
    'building': 'Корпус 2',
    'room': '315',
    'icon': 'analytics',
    'color': '#00695C',
  },
];
